### ISSUE TITLE
triggered and timed cleanup don't work

### ISSUE THREAD

**Issue by 88tom** [SEServerExtender/EssentialsPlugin#2]
hi! the cleanup doesnt read the scancommand fields.. i wrote inside it and the report was blank... so it delete all :/

**Comment by yaccoin** [comment]
Note this is discussed in the Extender Issues area as well...

**Comment by dodexahedron** [comment]
Yikes.
Yeah, I'm aware I broke some of the argument parsing.
It seems that blockcount and noownership currently work correctly.
The rest I am going to have to test manually and be sure I get them fixed up.
I'll get to that as soon as I possibly can, before I continue work on new stuff in SESE.

**Comment by yaccoin** [comment]
I'm not 100% sure that noownership is reporting everything.  I tried it 
this evening, after the server was running for 12 hours or so, and it 
only found one explorer ship.  Using SEToolbox I'm seeing dozens, as 
expected.  Suspect some chain is broken?

I am seeing a fair number of "Problem getting entities" messages on the 
console.

Cassey.

On 3/27/2015 12:49 AM, dodexahedron wrote:
>
> Yikes.
> Yeah, I'm aware I broke some of the argument parsing.
> It seems that blockcount and noownership currently work correctly.
> The rest I am going to have to test manually and be sure I get them 
> fixed up.
> I'll get to that as soon as I possibly can, before I continue work on 
> new stuff in SESE.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/SEServerExtender/EssentialsPlugin/issues/2#issuecomment-86834912>.
>
w

**Comment by dodexahedron** [comment]
You tried from the most recent version?
I didn't change its logic - only fixed the argument parser for it.  It should, in theory, behave exactly as it did before, since I didn't change the actual scan logic.

**Comment by yaccoin** [comment]
1.074.11 version

**Comment by yaccoin** [comment]
Happy to report that 1.75.6.335 was just installed and found 65 matrixes with no ownership!  From what I could tell, all were explorer ships.

**Comment by dodexahedron** [comment]
Can you try again with the latest release and let me know how it works?

**Comment by dodexahedron** [comment]
Pretty sure this is fixed.
Closing.
If it still acts up, feel free to re-open.
