### ISSUE TITLE
Compiling Server Essentials

### ISSUE THREAD

**Issue by Ragnar24** [SEServerExtender/EssentialsPlugin#21]
Hey dodexahedron,

If you have time, I could use help with finding the directory for SEMod.api.utility this is the only reference I need to be able to compile server essentials.

My plan is to dig through and find out how and why the turret management is not working. 

I have looked through SE Server Extender and Essentials files from Tyrsis, you, chess, etc. And I have not been able to find a Utility under that directory.

Thanks in advance,
Ragnar

**Comment by dodexahedron** [comment]
You need to reference semodapi.dll, semodapionternal.dll, and semodapiextensions.dll from extender.
Those are the files essentials is looking for.

-----Original Message-----

**Comment by Ragnar24** [comment]
Thank you for the fast reply. 

I already have those files added but for the Core.cs file I'm getting this error:

Error	6 The type or namespace name 'Utility' does not exist in the namespace 'SEModAPI.API' (are you missing an assembly reference?)

on line 34: using SEModAPI.API.Utility

Is there something else that i'm missing other than what's been mentioned above? Or do I have the wrong version of Essentials?

I am using SESE v1.74.10.288-alpha and Essentials v1.11.1.2386

**Comment by dodexahedron** [comment]
You should be using the current version of SEServerExtender and EssentialsPlugin from github.
Here's the easiest way to get up and running.

Check both projects out into the same root folder.  ie c:\Dev\SE\
You will then end up with `c:\Dev\SE\EssentialsPlugin` and `c:\Dev\SE\SEServerExtender`

Next, compile SEServerExtender in x64 release mode in visual studio (the project configuration of Essentials looks in that particular output path).

Next, open up EssentialsPlugin and you should be able to build.

I just repeated those steps on this machine and it worked.
Let me know how you fare.

**Comment by Ragnar24** [comment]
Thank you very much for taking your time to help the SE community. I will definitely try to help as much as I can, but seeing I've only had 3 semesters of very basic programming it might take me a little bit to catch up.

**Comment by zrisher** [comment]
@dodexahedron's info above should be placed in the readme under "Installation" where it talks about compiling from source.

**Comment by dodexahedron** [comment]
It'll go on the wiki.
I'll probably put that on the readme.md here, as well.

**Comment by zrisher** [comment]
By `that` you mean [this wiki](http://wiki.seserverextender.com/wiki/Main_Page) right? That would be great, yes please.

Github has project wikis, moving to that format could possibly save you some time maintaining that site in the long run.
