### ISSUE TITLE
Shipyards feature missing

### ISSUE THREAD

**Issue by zrisher** [SEServerExtender/EssentialsPlugin#24]
I can't find anything in here about the "Shipyards" feature that was once part of essentials - it would allow you to construct and deconstruct ships within a beacon frame. It was a handy alternative to projectors and lag from welding/grinding. Is that no longer available?

**Comment by dodexahedron** [comment]
Shipyards were never a feature of essentials. That’s a separate plugin that Tyrsis never shared the source code for.

Essentials has docks, which are just for putting ships away when you’re not using them.

**Comment by zrisher** [comment]
Could this be a proposed feature?

**Comment by dodexahedron** [comment]
As a separate plugin, sure.
Plugins are pretty easy to write, and the rules for a shipyard plugin that works the way people have described Tyrsis' shipyard plugin shouldn't be too terribly difficult to write.
Are you interested in perhaps spearheading that?
I'll throw a new project in the org and give you read/write if you are.

**Comment by zrisher** [comment]
Unfortunately I'm fairly C# illiterate (working on it), and my free time right now is mostly taken up just trying to keep my server stable. As soon as it gets there I'll have time to assist and would love to help. But conquest mode would be my most pressing need so that would be first priority.
