### ISSUE TITLE
Docking may lose track of docked ships

### ISSUE THREAD

**Issue by zrisher** [SEServerExtender/EssentialsPlugin#28]
Hi guys, some of the players in my server report that Transcend has disabled docking because ships have started dissappearing from their lists. This is what Tyrsis said on his server's steam page:

> tyrsis  Officer Apr 20 @ 7:05am 
It appears the game may be renumbering grids when they shouldn't be. I will have to look at it, but  for now will disable docks. There's not a lot I can do to recover stuff when Keen decides to change something without actually telling anyone.

Can someone else confirm this is a current problem? I don't want to enable it and have my users ships become difficult to recover.

**Comment by dodexahedron** [comment]
Interesting.
I'll play with it and see if I can repro

**Comment by markam67** [comment]
I use docking on my server but most only use it very limited, that said I have not seen this issue currently and have repeatedly docked/undocked ships in the current server world that has been restarted many times (due to current memory leak issue somewhere)

**Comment by dodexahedron** [comment]
I've never been able to reproduce this issue, either.
