### ISSUE TITLE
Essentials 1.12.0.2399 - /admin commands

### ISSUE THREAD

**Issue by xxam** [SEServerExtender/EssentialsPlugin#31]
If i use /admin scan grids i get the message that it found 0 grids. (the server has plenty of grids on it)
also if i use /delete all floating objects i get the message that 0 were deleted. - while i get this message the floating objects will still be deleted.

**Comment by zrisher** [comment]
I've found that if you use the extender commands:
 `/list all` (will give you zero entities)
 `/list all` again (will give you correct num entities)
and then `/admin scan grids` will sometimes be updated to the correct number.

**Comment by tdmike** [comment]
I think this is caused by the entity tab not properly updating at times, I have these issues myself atm.

**Comment by dodexahedron** [comment]
I'll have a look into this as soon as I can.
I'm thinking using the mod api for things was apparently a bad idea.

**Comment by xxam** [comment]
whatever you did, the new server extender with the new essential version seems to have done the trick. /admin scan commands now working properly.
