### ISSUE TITLE
Protected Entities Not Working

### ISSUE THREAD

**Issue by SavagerX** [SEServerExtender/EssentialsPlugin#36]
As the title says, protected entities no longer seem to be working. The log merely spams "protecting grid" & "repaired grid" a billion times over yet you can still damage the grid with ramming or angle grinders. 

I looked on the forums and it would appear that this was not the first time this kind of issue happened.

http://forum.keenswh.com/threads/se-server-extender-current-releases-and-plugins.7333303/page-7#post-1286754343

I am using SE-EP v 1.12.3.2412 and SESE v 1.80.11.476

**Comment by k4n30** [comment]
:+1:

**Comment by DigTron** [comment]
I'm seeing this too, no repair takes place. Not exactly a grid refresh moment but doing one stops it posting so I assume it stops it from continuing to try. The same happens when the grid becomes concealed, stops posting 'protecting/repaired grid' and the grid remains damaged.
