### ISSUE TITLE
Question Not Issue

### ISSUE THREAD

**Issue by Lordicon** [SEServerExtender/EssentialsPlugin#4]
Is the Block Enforcement working or is it still broken? If its broken then what's the best way to set the cleanup? Timed or Triggered and how would I set the cleanup all in one command instead of having them in their own?

**Comment by zrisher** [comment]
I suggest this be renamed to "Is block enforcement working?". Like probably many others, I'm still trying to work out the kinks with other aspects of this plugin so I'm not sure of the answer. I'm guessing there are many posts in the other repos / forums / steam that could tell us what the current issues are, but if anyone is aware of them it would be great to centralize here.

**Comment by stephen-cernota** [comment]
Lordicon, I believe you're confusing two different sets of functionality:
Grid Cleanup (timed/triggered) and Block Enforcement (auto/real time)

Both seem to have been fixed by Dox (WOOT!):
 - triggered and timed cleanup don't work #2 
 - Block enforcement not working #14

**Comment by dodexahedron** [comment]
Closing this issue, as it was answered long ago.
Also, just noting that technically all actions essentials carries out are "timed."  They all run on timers, so even the most "real-time" of them still only executes something like every 1 second.
That's not me being pedantic so much as it's me clarifying its behavior so you better understand how it interacts with your game.
