### ISSUE TITLE
Dynamic Entity Management causing huge delays

### ISSUE THREAD

**Issue by wweiland** [SEServerExtender/EssentialsPlugin#41]
We've started to experience a problem, starting a couple of revisions ago, where we are unable to grind, weld, or move inventory for several seconds to minutes.  It randomly affects people sometimes at the same time and sometimes not.  The game and network logic had low numbers at the time of the occurrences.  During troubleshooting, I turned off the DEM and the issue no longer presented itself.  We have been running 24 hours now with no issues.  If anything is needed, please let me know.

Thanks

**Comment by dodexahedron** [comment]
This is odd.
Can you give me a copy of your world?
I'd like to test this out.
Does this happen when there's only a single player connected?
