### ISSUE TITLE
/motd broken

### ISSUE THREAD

**Issue by DigTron** [SEServerExtender/EssentialsPlugin#44]
Not all that important right now but will need fixing, I'll try later if I get the time. Its not showing in latest version, think what handles those boxes has changed some. 

A clue was in the change notes "- fixed single and multiline textboxes (by LordDevious)". 

http://forum.keenswh.com/threads/update-01-085-improved-ship-navigation-docking.7361477/

**Comment by DigTron** [comment]
https://github.com/KeenSoftwareHouse/SpaceEngineers/pull/205

**Comment by SilentSymphony** [comment]
Mine be broken as well.

**Comment by dodexahedron** [comment]
Wait, so what's the problem you're reporting?
I don't quite parse your initial message.
And from what I can see, there's nothing in that PR that actually directly affects this.

**Comment by SilentSymphony** [comment]
/motd results in

|Info|EssentialsPlugin.Essentials.HandleChatMessage|ChatHandler Error: System.NullReferenceException: Object reference not set to an instance of an object.
   at EssentialsPlugin.ChatHandlers.HandleMotd.HandleCommand(UInt64 userId, String[] words)
   at EssentialsPlugin.Essentials.HandleChatMessage(UInt64 steamId, String message)

I've tried revealing the global array but /admin reveal force seems to do nothing and cause people to be unable to join.

**Comment by SilentSymphony** [comment]
This has been broken for over 2 weeks now, join messages & /motd neither work

**Comment by dodexahedron** [comment]
I don't really have the time to do much actual troubleshooting, for the next couple of weeks.
My wedding is next saturday, so things are a little crazy.
If someone else wants to take a crack at it and submit a PR, I'm more than happy to merge a fix, but right now I don't have the time to investigate until all the wedding stuff is done.

**Comment by SilentSymphony** [comment]
Well thanks for the info, And best of luck ;)

**Comment by dodexahedron** [comment]
Grr. I tried to troubleshoot this one today, but the game kept causing my computer to power off, so I got frustrated and stopped.
I'll take another crack at it another night.
