### ISSUE TITLE
Asteroid Streaming not working

### ISSUE THREAD

**Issue by SilentSymphony** [SEServerExtender/EssentialsPlugin#47]
Since the feature was added it has done absolutely nothing despite the wvm argument in place and the essentials settings turned on.

**Comment by Chuuthulhu** [comment]
I'm having the same issue. 

 I'm using the command "C:\xxxx\xxxxx\xxxxx\DedicatedServer\DedicatedServer64\SEServerExtender.exe wvm autostart" and it tells me that it loads correctly with 2 arguments and autostarts as it's supposed to, but the world size doesn't reduce, speed has definitely not improved on the server and there aren't any conceal messages for asteroids when i turn on logging in the settings of the plugin.

**Comment by Tyrsis** [comment]
I think I left out the fact that wrr needs to be in the command line as well.  Oops.

**Comment by SilentSymphony** [comment]
Working with wrr and wvm now.

**Comment by Chuuthulhu** [comment]
Same issue. world size dropped from 8mb to 3mb, asteroids were not appearing. Tried enabling/disabling in Essentials, tried reducing conceal distance at 25000m 20,000m 18,500m, and restarted with argument before and after wvr. 

Removed argument as well until further notice.

**Comment by Tyrsis** [comment]
Essentials requires a small update to add the voxel processor to the process handler.  I advised dode how to fix it.  Should be in an update when he gets to it.
