### ISSUE TITLE
[improvement] Dynamic Concealment Owner Settings

### ISSUE THREAD

**Issue by SilentSymphony** [SEServerExtender/EssentialsPlugin#48]
Currently dynamic concealment detects grids with a medbay or any other blocks you have configured, This works well enough but the ships are not concealed when the user logs out.

I think it would be better if when the owner logs out their ships are concealed.

This could be an additional setting that bypasses the settings for medbay/additioinal blocks to stop essentials from hiding the ship

**Comment by dodexahedron** [comment]
And then would they un-hide when the player joins again?

**Comment by SilentSymphony** [comment]
The ships that fit the medbay and block whitelist settings would reveal when they join yes.
