### ISSUE TITLE
[SOLVED] (as best it can be for now) Most Large Grids not concealing

### ISSUE THREAD

**Issue by FoxWyvern** [SEServerExtender/EssentialsPlugin#49]
Most Large Grids on my server are not concealing. Most of them being stations. Have no idea why, did a lot of testing and tried various blocks that might be preventing one station and/or ship being concealed while allowing others but to no avail.

**Comment by FoxWyvern** [comment]
Additionally, I have finally realized which grids won't conceal. It's any grid that has another entity attached either through a "LOCKED" Connector, Landing Gear, Rotor, or Piston. I believe one of my admins told me that Merge blocks were ok as they create a single entity when merged. Additionally, removing the head of a piston or rotor  suddenly allows stations/ships to be concealed. I've also noticed that the /admin scan grids "hasdisplayname:DISPLAY NAME HERE" command does not owrk on any of these grids that have an attached entity. Has it always been this way or is this a more recent bug that hopefully can be fixed in the future?

**Comment by dodexahedron** [comment]
Good troubleshooting.
I will have a look at this when I am home.

-----Original Message-----

**Comment by FoxWyvern** [comment]
I want to say I'm no longer confident of Landing Gear preventing one or more grids from concealing. I honestly am not sure and wish I had done some additional testing. Due to work, I'll be unable to do any more additional testing for a few days, but I'll hopefully catch one of my admins and instruct them on some additional for landing gear.

I can say for sure, that large grids that are properly concealing, will be prevented from concealing by adding a rotor with rotor top, and piston with piston top. As well as a connector being in the locked position.

I have not specifically gone through and removed existing rotors/pistons/locked connectors from stations already unable to conceal prior to my testing.

Additionally, /admin scan grids "hasdisplayname:DISPLAY NAME HERE" command was used without success on grids that could not already conceal prior to testing. I did not specifically remember attempting the command on a grid that I forced to be unable to conceal by adding a rotor or grid. I wish I had time to hop on for an hour or so to hammer these questions out to make them absolute but figured I'd at least mentioned what wasn't done so not to lead you astray.

Anyone else who reads this is also welcome to pick up my slack. I apologize, it was quite late when we were discovering this.

**Comment by Tyrsis** [comment]
If a ship is connected they will not be concealed.  This is by design due to the fact that concealing connected ships used to cause run away memory leaks.  Also if you conceal a ship that is connected via rotor or piston, the rotor head / piston head will disappear.

**Comment by FoxWyvern** [comment]
Sad times, so many complex structures use pistons/rotors.. hopefully keen adjusts this in the near future but i won't hold my breath.
