### ISSUE TITLE
[BUG] /admin reveal force - unresponsive server

### ISSUE THREAD

**Issue by FoxWyvern** [SEServerExtender/EssentialsPlugin#53]
The command /admin reveal force makes the server unresponsive. Main server auto restarted due to being unresponsive. Waited 500 seconds on test server, quit, and attempted to rejoin without success.

**Comment by FoxWyvern** [comment]
This is true for both Essentials .2441 and .2443, however I seem to remember the command working prior to the patch. I am no longer getting the usual spam of reveal entitys and flood of concealed entitys showing in the logs. Instead the server sits there and hangs with the following:

2015-06-18 00:13:38.1781|Info|COMMAND 144115188075855874 - 183141911269046762: /
admin reveal force
2015-06-18 00:13:38.2231|Info|Conceal

**Comment by FoxWyvern** [comment]
To clarify, I remember it working 8 days ago before keens patch, not essentials update from a couple days ago, even though there was another essentials update on the same day as keens patch to keep it compatible.

I attempted to turn off Dynamic Conceal on my test server since I don't really see a point in using the command if you have Dynamic Conceal enabled. I ran the command but sadly the result was the same, with the same crappy log as stated above.

The actual log file only lists the following after the command is used:

2015-06-18 18:12:29.3605|Info|EssentialsPlugin.ChatHandlers.AdminConceal.HandleAdminReveal+<>c__DisplayClass4.<HandleCommand>b__2|Conceal

**Comment by Chuuthulhu** [comment]
Also having the same issue. Server becomes unresponsive immediately after issuing command.  I have attempted it with concealment enabled/disabled.

**Comment by FoxWyvern** [comment]
Retested and still an issue as of:

Space Engineers: 01.087.007 (SESE: 1.86.08.530 - Essentials: 1.13.2.2443 - Get Out Of My Sandbox: 1.0.1.53)

**Comment by wweiland** [comment]
I too have this problem.  I want to turn off the entity management as I think it is causing delay, but unable to do so because I can't reveal hidden ships.  Thanks.

**Comment by Chuuthulhu** [comment]
If you were to turn off dynamic concealment, you can reveal everything by editing the XML and replacing all instances of  >CastShadows<  with  >CastShadows InScene<

**Comment by wweiland** [comment]
Which xml file do I need to edit?

**Comment by wweiland** [comment]
nevermind, found it.  Thanks again.

**Comment by FoxWyvern** [comment]
I'm not sure if this is a [BUG] as I do not know if this has always been and just relyed on server admins to use the command /admin reveal force to fix this, or if the server was suppose to reveal everything when Dynamic Conceal was disabled. So I'm posting it here for now.

Setting Dynamic Entity Management: Eneabled = False does not reveal any concealed grids and when a player arrives at the grid, the grids stay concealed. because of course the Dynamic Entity Management has been turned off...

Additionally, I would like to add that without the /admin conceal force ability, testing entity's for reasons why they are not concealing has become very very difficult. I would like to stress that I've never needed that command to work more than I do now and it broke on the week that I really need it to find additional bugs with Dynamic Conceal.

**Comment by FoxWyvern** [comment]
Just found after updating /admin conceal works, and it doesn't matter what I put after the command as it doesn't do what I thought it did. Instead it's just a command for showing info on current concealed objects. Which of course doesn't help me with my troubleshooting and now I want to make another request post LOL ><
