### ISSUE TITLE
[BUG] /admin scan grids "ownedby:Neutral NPC"

### ISSUE THREAD

**Issue by FoxWyvern** [SEServerExtender/EssentialsPlugin#59]
This command has always only returned one result for me, regardless of how many grids are actually owned by "Neutral NPC" assuming there isn't 0.

I've tested this by allowing multiple cargo ships to spawn then using the command /admin scan grids "ownedby:Neutral NPC" . Then deleteing the returned resulting grid with the "hasdisplayname:Large Ship ###" command. Then repeating the /admin scan grids "ownedby:Neutral NPC" only to have a different grid come back as a result.

Additionally, using the filter ownership and noownership combined with the "ownedby:Neutral NPC" returns the same results.
/admin scan grids ownership "owendby:Neutral NPC"
/admin scan grids noownership "ownedby:Neutral NPC"

This issue has been true since I first started using essentials and I just forgot about it until I revisted attempting to provide a way to have cargo ships on my server again.

**Comment by McyD** [comment]
Second this one, as using Hostile Universe mod means that a lot of these ships show up, and the server loses track of them on restarts.  Without this working there are a lot of ships owned by Neutral NPC that have to be manually removed.
