### ISSUE TITLE
Block Enforcement Broken with Space Engineers Update 1.091

### ISSUE THREAD

**Issue by afinegan** [SEServerExtender/EssentialsPlugin#66]
I am pretty sure the BlockEnforcement module is currently broken. This is the error below.

Error:
2015-07-16 14:35:32.8997|Error|System.MissingMethodException: Method not found:
'System.Collections.Generic.List`1<Sandbox.ModAPI.Ingame.IMyTerminalBlock> Sandb
ox.ModAPI.Ingame.IMyGridTerminalSystem.get_Blocks()'.
   at EssentialsPlugin.ProcessHandlers.ProcessBlockEnforcement.ScanForBlockItems
()
   at EssentialsPlugin.ProcessHandlers.ProcessBlockEnforcement.Handle()

**Comment by devu** [comment]
Indeed

**Comment by EngineerBean** [comment]
Can also confirm this on my DS..

**Comment by SilentSymphony** [comment]
Same here.

**Comment by afinegan** [comment]
This is the changefix from a fork which should give you hints on how to fix ti here, if its not fixed by the time I get home, I might have to breakout the c# lol

https://github.com/TheEngineer50/EssentialsPlugin-FC-Alpha/commit/9cba33289cb8ff7e2cfd42abd5ccaf53742836f2

**Comment by GlassyAndroid** [comment]
2015-07-21 00:57:20.8913|Error|System.MissingMethodException: Method not found: "
System.Collections.Generic.List`1<Sandbox.ModAPI.Ingame.IMyTerminalBlock> Sandbo
x.ModAPI.Ingame.IMyGridTerminalSystem.get_Blocks()".
   в EssentialsPlugin.ProcessHandlers.ProcessBlockEnforcement.ScanForBlockItems(
)
   в EssentialsPlugin.ProcessHandlers.ProcessBlockEnforcement.Handle()

Someone decided this issue ?

**Comment by dodexahedron** [comment]
This has been fixed in version 2252, which will be released shortly.
