### ISSUE TITLE
Essentials Update?

### ISSUE THREAD

**Issue by EngineerBean** [SEServerExtender/EssentialsPlugin#74]
Hey there Dodexahedron,

Hope all is well for you etc. I am wondering as I expect other server admins are too as to when you plan to update essentials. Many of us have become quite reliant on SESE and Essentials to run our servers with as Keen have never provided anything nearly as useful as what has been created by the community. I'm sure I can speak for all SE server admins that your efforts have been greatly appreciated in keeping this project active for the community. If you are needing help on this project be sure to let the SE community know, i'm sure there would be others out there willing to do so.

Keep up the great work Dodex..

**Comment by GornyakManiac** [comment]
+

**Comment by dodexahedron** [comment]
There are multiple issues, and I'd be happy to discuss with you if you want to hop on our teamspeak server. Information is at www.ticfleet.com on the right side of the page. My handle there is the same as here. I'm generally there after 10PM US Eastern time and not on weekends.
