### ISSUE TITLE
reserve slots

### ISSUE THREAD

**Issue by TheEngineer50** [SEServerExtender/EssentialsPlugin#81]
My server has 25 player limit. I setup reserve slots with 1 slot. admins only.

It was telling non admins the server was full at around 12 people. 

:/

**Comment by rexxar-tc** [comment]
When an admin connects, the log should spit out a line like "1 of 1 slots allocated", same when they disconnect. Do these numbers match up to what's actually happening in the game?

**Comment by TheEngineer50** [comment]
http://pastebin.com/SwzVb32R

**Comment by rexxar-tc** [comment]
I forgot to mention that the last update includes improved logging. Try again with the debug option ticked and post the log if you're still having trouble.

**Comment by TheEngineer50** [comment]
this is working ok now.
