### ISSUE TITLE
v1.13.5.353 - Chat commands repeated five times

### ISSUE THREAD

**Issue by mookfist** [SEServerExtender/EssentialsPlugin#84]
Any chat command I type is repeated five times. /motd for example, requires you to close five of them.

**Comment by mookfist** [comment]
it seems the number of times a command is repeated is not set at 5.

typing into chat /motd yesterday generated the motd window seven times. Same thing for other commands like /help

**Comment by rexxar-tc** [comment]
Did today's SESE update fix it for you?
