### ISSUE TITLE
Entity Management

### ISSUE THREAD

**Issue by TheEngineer50** [SEServerExtender/EssentialsPlugin#85]
Is it currently in a working state?

When I try to use it I have grids that are missing all of the functional blocks, the armor blocks I can fly through and a lot of grids are simply missing. 

Full of these errors:

https://pastee.org/h4xe5

**Comment by TheEngineer50** [comment]
Looks like a recompile fixed it

**Comment by TheEngineer50** [comment]
Nope, was something else. Delete/close this please

**Comment by rexxar-tc** [comment]
The physics-less armor blocks is some sort of bug in SE that I've never really bothered to investigate. When a grid is concealed it leaves that behind for some reason. I kind of like it, actually, it lets you still see that there's something there.

That cast exception is interesting though, I'll have to investigate that.

And by the way, you can close issues yourself :)
