### ISSUE TITLE
Console Error every few minutes and on load

### ISSUE THREAD

**Issue by demolish50** [SEServerExtender/EssentialsPlugin#9]
System.TypeLoadException: Could not load type 'NLog.Fluent.Log' from assembly 'NLog, Version=3.2.0.0.

**Comment by dodexahedron** [comment]
Can you give me the entire log entry?
I need to know where it happened (ie the stack trace).

**Comment by dodexahedron** [comment]
I found what is causing this.
Commit is coming in a few seconds and the fixed release will be out when I get home in like 30 minutes.
