### ISSUE TITLE
Dynamic Entity Management Broken

### ISSUE THREAD

**Issue by kirock** [SEServerExtender/EssentialsPlugin#95]
Dynamic Entity Management Broken, no grids conceal at all, as a result - simulation speed 0.5 at start with 0 online. /admin conceal shows that 216 grids are concealed, but they are not. Going to use previous version.

**Comment by kirock** [comment]
Talking about v1.13.7.01-alpha (Latest release for now) version.

**Comment by rexxar-tc** [comment]
Grids don't actually get concealed anymore, did you read the update blog? They aren't removed from the world at all, so you still see them.

**Comment by kirock** [comment]
I did. Just talking about the sim speed, server is now unplayable due too many grids. Because they are not concealed anymore... Thats a difficult situation here...

**Comment by Tostito** [comment]
wanted to leave my feedback on this subject.  after i got my box working my server is able to hit 1.0 server simulation but with frequent dips that ive seen hit .17 server sim.  at first i thought perhaps this was combat or collision from revealed grids (from the old system) however after tabbing around to different grids in space master i could not find any evidence of  collisions or any ongoing combat. my server uses pirates so random combat is a possibility. i reverted back to the old conceal method using the same save and the server sim dips stopped.

**Comment by rexxar-tc** [comment]
If it says in the log that it concealed something, then it did. The concealment method is so simple that there really is not anything that would fail in such a way that **no** grids are concealed. I mean, it literally just turns off some flags and removes the entity from a list. The only other significant thing is that physics is still active on those grids, which shouldn't really cause an issue.

I do have an idea though, I'll tweak some things and push a new update sometime later tonight.

**Comment by Tostito** [comment]
if we turn off physics do we need to then bounce the server to get that to take affect?

**Comment by rexxar-tc** [comment]
I have no idea what you mean. You don't need to do anything other than set that option.

**Comment by rexxar-tc** [comment]
This should be fixed in the latest update.
